spring:
  application:
    name: loans

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/loanservice
    username: loanserviceuser
    # password: ${PRODUCT_SERVICE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8090

#http://localhost:8090/swagger-ui/index - swagger ui url