spring:
  application:
    name: Accounts

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/accountservice
    username: accountserviceuser
    # password: ${PRODUCT_SERVICE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
